"""
CONFIGURAÇÃO DO AGENTE ESTUDIOSO - VERSÃO SIMPLIFICADA
"""

# ATIVOS PARA MONITORAR
ATIVOS = [
    "EURUSD",
    "GBPUSD",
    "USDJPY",
    "GBPJPY",
    "AUDUSD",
    "USDCAD",
    "BTCUSD",
    "ETHUSD"
]

# TIMEFRAMES
TIMEFRAMES = ["1", "5", "15", "30"]

# CONFIGURAÇÕES
SCORE_MINIMO = 75
PROBABILIDADE_MINIMA = 65
VOZ_IDIOMA = "pt"
DB_MEMORIA = "memoria.db"
DB_TRADES = "trades.db"
